Order/Order/Models/Order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

Order/Order/Models/Orders.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        [Display(Name = "訂單編號")]
        public int OrderID { get; set; }
        [Required]
        [Display(Name = "客戶名稱")]
        public Nullable<int> CustomerID { get; set; }
        [Display(Name = "負責員工名稱")]
        public int EmployeeID { get; set; }
        [Display(Name = "訂購日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime OrderDate { get; set; }
        [Display(Name = "需要日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime RequiredDate { get; set; }
        [Display(Name = "出貨日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ShippedDate { get; set; }
        [Display(Name = "出貨公司名稱")]
        public int ShipperID { get; set; }
        [Display(Name = "運費")]
        public decimal Freight { get; set; }
        [Display(Name = "出貨說明")]
        public string ShipName { get; set; }
        [Display(Name = "出貨地址")]
        public string ShipAddress { get; set; }
        [Display(Name = "出貨城市")]
        public string ShipCity { get; set; }
        [Display(Name = "出貨地區")]
        public string ShipRegion { get; set; }
        [Display(Name = "郵遞區號")]
        public string ShipPostalCode { get; set; }
        [Display(Name = "出貨國家")]
        public string ShipCountry { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual OrderDetails OrderDetails2 { get; set; }

        public virtual Shippers Shippers { get; set; }
    }
}

Order/Order/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Order.Models;
using LinqKit;

namespace Order.Controllers
{
    public class OrdersController : Controller
    {
        private TSQL2012Entities db = new TSQL2012Entities();

        // GET: Orders
        public ActionResult Index(string orderID, string customerName, string employees, string companyName, string orderDate, string shippedDate, string requiredDate)
        {
            IQueryable<Orders> orders = db.Orders;

            ViewBag.employees = new SelectList(db.Employees, "EmployeeID", "FullName");
            ViewBag.companyName = new SelectList(db.Shippers, "ShipperID", "CompanyName");

            var pred = PredicateBuilder.True<Orders>();

            if (!String.IsNullOrEmpty(orderID))
            {
                pred = pred.And(x => x.OrderID.ToString().Equals(orderID));
            }

            if (!String.IsNullOrEmpty(customerName))
            {
                pred = pred.And(x => x.Customers.CompanyName.Contains(customerName));
            }

            if (!String.IsNullOrEmpty(employees))
            {
                pred = pred.And(x => x.EmployeeID.ToString().Equals(employees));
            }

            if (!String.IsNullOrEmpty(companyName))
            {
                pred = pred.And(x => x.Shippers.ShipperID.ToString().Equals(companyName));
            }

            if (!String.IsNullOrEmpty(orderDate))
            {
                DateTime orderDt;
                DateTime.TryParse(orderDate, out orderDt);
                pred = pred.And(x => x.OrderDate==(orderDt));
            }

            if (!String.IsNullOrEmpty(shippedDate))
            {
                DateTime shippedDt;
                DateTime.TryParse(shippedDate, out shippedDt);
                pred = pred.And(x => x.ShippedDate==(shippedDt));
            }

            if (!String.IsNullOrEmpty(requiredDate))
            {
                DateTime requiredDt;
                DateTime.TryParse(requiredDate, out requiredDt);
                pred = pred.And(x => x.RequiredDate==(requiredDt));
            }
            return View(orders.AsExpandable().Where(pred).Include(o => o.Employees).Include(o => o.Customers).Include(o => o.Shippers).ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = db.Orders.Find(id);
            if (orders == null)
            {
                return HttpNotFound();
            }
            return View(orders);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            List<Double> price = new List<Double>();
            List<int> pname = new List<int>();

            foreach (var item in db.OrderDetails)
            {
                price.Add(Decimal.ToDouble(item.Products.UnitPrice));
                pname.Add(item.Products.ProductID);
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName");
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CompanyName");
            ViewBag.ShipperID = new SelectList(db.Shippers, "ShipperID", "CompanyName");
            ViewBag.productName = new SelectList(db.Products, "ProductID", "ProductName");
            ViewBag.unitPrice = price;
            ViewBag.proName = pname;
            return View();
        }

        // POST: Orders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipperID,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry,productName,UnitPrice,Qty")] Orders orders)
        {
            if (ModelState.IsValid)
            {   
                orders.Freight = (string.IsNullOrEmpty(orders.Freight.ToString())) ? 0 : orders.Freight;
                orders.ShipCountry = (string.IsNullOrEmpty(orders.ShipCountry)) ? string.Empty : orders.ShipCountry;
                orders.ShipCity = (string.IsNullOrEmpty(orders.ShipCity)) ? string.Empty : orders.ShipCity;
                orders.ShipRegion = (string.IsNullOrEmpty(orders.ShipRegion)) ? string.Empty : orders.ShipRegion;
                orders.ShipPostalCode = (string.IsNullOrEmpty(orders.ShipPostalCode)) ? string.Empty : orders.ShipPostalCode;
                orders.ShipAddress = (string.IsNullOrEmpty(orders.ShipAddress)) ? string.Empty : orders.ShipAddress;
                orders.ShipName = (string.IsNullOrEmpty(orders.ShipName)) ? string.Empty : orders.ShipName;
                db.Orders.Add(orders);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName");
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CompanyName");
            ViewBag.ShipperID = new SelectList(db.Shippers, "ShipperID", "CompanyName");
            ViewBag.productName = new SelectList(db.Products, "ProductID", "ProductName");
            return View(orders);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = db.Orders.Find(id);
            if (orders == null)
            {
                return HttpNotFound();
            }
            List<Double> price = new List<Double>();
            List<int> pname = new List<int>();

            foreach (var item in db.OrderDetails)
            {
                price.Add(Decimal.ToDouble(item.Products.UnitPrice));
                pname.Add(item.Products.ProductID);
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName");
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CompanyName");
            ViewBag.ShipperID = new SelectList(db.Shippers, "ShipperID", "CompanyName");
            ViewBag.productName = new SelectList(db.Products, "ProductID", "ProductName");
            ViewBag.unitPrice = price;
            ViewBag.proName = pname;
            return View(orders);
        }

        // POST: Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipperID,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry,productName,UnitPrice,Qty")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                orders.Freight = (string.IsNullOrEmpty(orders.Freight.ToString())) ? 0 : orders.Freight;
                orders.ShipCountry = (string.IsNullOrEmpty(orders.ShipCountry)) ? string.Empty : orders.ShipCountry;
                orders.ShipCity = (string.IsNullOrEmpty(orders.ShipCity)) ? string.Empty : orders.ShipCity;
                orders.ShipRegion = (string.IsNullOrEmpty(orders.ShipRegion)) ? string.Empty : orders.ShipRegion;
                orders.ShipPostalCode = (string.IsNullOrEmpty(orders.ShipPostalCode)) ? string.Empty : orders.ShipPostalCode;
                orders.ShipAddress = (string.IsNullOrEmpty(orders.ShipAddress)) ? string.Empty : orders.ShipAddress;
                orders.ShipName = (string.IsNullOrEmpty(orders.ShipName)) ? string.Empty : orders.ShipName;

                db.Entry(orders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "LastName");
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CompanyName");
            ViewBag.ShipperID = new SelectList(db.Shippers, "ShipperID", "CompanyName");
            return View(orders);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = db.Orders.Find(id);
            if (orders == null)
            {
                return HttpNotFound();
            }
            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Orders orders = db.Orders.Find(id);
            db.Orders.Remove(orders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Order/Order/Views/Orders/Create.cshtml
@model Order.Models.Orders

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerID)
            </th>
            <td>
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })                
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeID)
            </th>
            <td>
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <td>
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </td>
            <th>
                @Html.DisplayNameFor(model => model.RequiredDate)
            </th>
            <td>
                @Html.EditorFor(model => model.RequiredDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.RequiredDate, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShippedDate)
            </th>
            <td>
                @Html.EditorFor(model => model.ShippedDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShipperID)
            </th>
            <td>
                @Html.DropDownList("ShipperID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipperID, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Freight)
            </th>
            <td>
                @Html.EditorFor(model => model.Freight, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Freight, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShipCountry)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipCountry, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipCountry, "", new { @class = "text-danger" })
            </td>
            <th>
                @Html.DisplayNameFor(model => model.ShipCity)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipCity, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipCity, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShipRegion)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipRegion, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipRegion, "", new { @class = "text-danger" })
            </td>
            <th>
                @Html.DisplayNameFor(model => model.ShipPostalCode)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipPostalCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipPostalCode, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShipRegion)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipRegion, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipRegion, "", new { @class = "text-danger" })
            </td>
            <th>
                @Html.DisplayNameFor(model => model.ShipPostalCode)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipPostalCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipPostalCode, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShipAddress)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipAddress, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
            </td>
            <th>
                @Html.DisplayNameFor(model => model.ShipName)
            </th>
            <td>
                @Html.EditorFor(model => model.ShipName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>訂單金額總計</th>
            <td id="total" colspan="4"></td>
        </tr>
        <tr>
            <td></td>
            <td colspan="4">
                <input type="submit" value="存檔"  />
                <input type="button" onclick="location.href='./Index';" value="回前一頁" />
            </td>
        </tr>
    </table>
    <a onclick="AddNewDetail()" href="#">新增一筆</a>
        <table class="table table-bordered">
            <tr>
                <td>商品</td>
                <td>單價</td>
                <td>數量</td>
                <td>小計</td>
                <td></td>
            </tr>
            <tbody id="detailContent">
                    <tr>
                        <td>@Html.DropDownList("productName", null , new  { @id = "DropdowmListProduct", @class = "ProductID", @onchange = "GetPrice(this)" })</td>
                        <td>@Html.TextBoxFor(model => model.OrderDetails2.UnitPrice, new { @class = "UnitPrice", @id = "UnitPrice", onchange = "ChangePrice(this)" })</td>
                        <td>@Html.TextBoxFor(model => Model.OrderDetails2.Qty, new { @class = "Qty", onchange = "Count(this)" })</td>
                        <td id="count"><input type="text"></td>
                        <td><button type="button" class="btnRemove">取消</button></td>
                    </tr>
            </tbody>
        </table>
}
<script>
    function AddNewDetail() {
        //明細資料範本
        var trtemplate = $('#detailContent tr').eq(0).html();
        //新增一列名資料
        $('#detailContent').append('<tr>' + trtemplate + '</tr>');

        //移除TR
        $('#detailContent').on('click', '.btnRemove', function () {
            $(this).closest('tr').remove();
        });

        for (var i = 0 ; i < $('#detailContent tr').length; i++) {
            $('.ProductID').eq(i).attr('name', 'OrderDetails[' + i + '].ProductID');
        }
    }


    function GetPrice(item) 
    {
        var uniPrice = @Html.Raw(Json.Encode(ViewBag.unitPrice));
        var proName = @Html.Raw(Json.Encode(ViewBag.proName));
       
        for (var i = 0;i<proName.length;i++){
            if(item.value==proName[i]){
                $(item).parent().next('td').children().val(uniPrice[i]);
                break;
            }
        }     
    }

    function Count(item){
        var unitprice = $(item).parent().prev('td').children().val();
        var qty = $(item).closest("input:text").val();
        var count = unitprice * qty;
        $(item).parent().next('td').children().val(count);
        Total(count);
    }

    function ChangePrice(item){
        var unitprice = $(item).closest("input:text").val();
        var qty = $(item).parent().next('td').children().val();
        var total = unitprice * qty;

        $(item).parent().next('td').next('td').children().val(total);
    }

    function Total(count){
        var countArray = [];
        var total = 0;
        for(var i=0;i<$('#detailContent tr').length;i++){
            countArray[i] = count;
            total += countArray[i];
        }

        document.getElementById("total").innerHTML = total;
    }

</script>

Order/Order/Views/Orders/Delete.cshtml
@model Order.Models.Orders

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Orders</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Freight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Freight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipRegion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipRegion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipPostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipPostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employees.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employees.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customers.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customers.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shippers.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shippers.CompanyName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Order/Order/Views/Orders/Index.cshtml
@model IEnumerable<Order.Models.Orders>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("Index", "Orders", FormMethod.Post))
{
    <p>
        <table class="table table-bordered">
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.OrderID)
                </td>
                <td>
                    @Html.TextBox("orderId", ViewBag.orderId as string, htmlAttributes: new { @class = "form-control" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Customers.CompanyName)
                </td>
                <td>
                    @Html.TextBox("customerName", ViewBag.customerName as string, htmlAttributes: new { @class = "form-control" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Employees.FullName)
                </td>
                <td> 
                    @Html.DropDownList("employees", string.Empty)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Shippers.CompanyName)
                </td>
                <td>
                    @Html.DropDownList("companyName", string.Empty)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </td>
                <td>
                    @Html.TextBox("orderDate", string.Empty, new { @class = "form-control", @type = "date" })
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.ShippedDate)
                </td>
                <td>
                    @Html.TextBox("shippedDate", string.Empty, new { @class = "form-control", @type = "date" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.RequiredDate)
                </td>
                <td>
                    @Html.TextBox("requiredDate", string.Empty, new { @class = "form-control", @type = "date" })
                </td>
            </tr>
        </table>
        <input type="submit" value="Search" />
        <input type="reset" value="Reset" onclick="clear()"/>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customers.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customers.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShippedDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OrderID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OrderID })
        </td>
    </tr>
}

</table>

<script type="text/javascript">
    function clear() {
        document.getElementById('orderId').value() = '';
        alert('123')
    }

</script>